[tool.ruff]
line-length = 88

# 除外するファイル
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pycache__",
]

# リント設定
[tool.ruff.lint]
# 有効にするルール
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "ANN", # flake8-annotations
    "S",   # flake8-bandit
    "A",   # flake8-builtins
]

# 無視するルール
ignore = [
    "ANN101",  # Missing type annotation for `self` in method
    "ANN102",  # Missing type annotation for `cls` in classmethod
    "ANN401",  # Any type allowed
    "E501",    # Line too long (特に文字列リテラルの場合)
]

# 自動修正可能なルール
fixable = ["ALL"]
unfixable = []

# isort設定
[tool.ruff.lint.isort]
known-first-party = ["app"]

# フォーマット設定
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

